import type { Metadata } from "next";
import { Questrial } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const questrial = Questrial({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-questrial",
});

export const metadata: Metadata = {
  title: "Codefend",
  description: "Generated by create next app",

};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </Head>
      <body className={`${questrial.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}


